#!/usr/bin/with-contenv bash

# This is the init file used for adding os or pip packages to install lists.
# It takes advantage of the built-in init-mods-package-install init script that comes with the baseimages.
# If using this, we need to make sure we set this init as a dependency of init-mods-package-install so this one runs first

if ! command -v git; then
    echo "**** Adding git and its deps to package install lists ****"
    echo "git" >> /mod-repo-packages-to-install.list
else
    echo "**** git already installed, skipping ****"
fi

if ! command -v pip; then
    echo "**** Adding pip and its deps to package install lists ****"
    ## Ubuntu
    if [ -f /usr/bin/apt ]; then
        echo "\
            python3 \
            python3-pip \
            python3-build" >> /mod-repo-packages-to-install.list
    fi
    # Alpine
    if [ -f /sbin/apk ]; then
        echo "\
            python3 \
            py3-pip \
            py3-build" >> /mod-repo-packages-to-install.list
    fi
else
    echo "**** pip already installed, skipping ****"
fi
