#!/usr/bin/with-contenv bash

# This is an install script that is designed to run after init-mods-package-install
# so it can take advantage of packages installed
# init-mods-end depends on this script so that later init and services wait until this script exits

# Clone deluge-ltconfig repo
mkdir -p /usr/src && cd $_
git clone https://github.com/ikari7789/deluge-ltconfig.git -b feature/fix-syntax

# Build egg
cd deluge-ltconfig
python setup.py bdist_egg

# Copy into plugins folder
s6-setuidgid abc mkdir -p /config/plugins/
s6-setuidgid abc rm -f /config/plugins/ltConfig-*.egg
s6-setuidgid abc cp ./dist/ltConfig-*.egg /config/plugins/